// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DemoCal.IntermediateRouting.Models
{
    /// <summary>
    /// Multiple Response Types Routing, Resultado
    /// </summary>
    public partial class MultipleRouteOperationNumeroReferenciaGet
    {
        


        public Routing Routing { get; set; }


        public Resultado Resultado { get; set; }
    } // end class

} // end Models namespace

