// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DemoCal.IntermediateRouting.Models
{
    public partial class Resultado
    {
        

        /// <summary>
        /// Descripción de la respuesta
        /// </summary>
        [Required]
		[JsonProperty("descripcion")]
        public string Descripcion { get; set; }
    } // end class

} // end Models namespace

