// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DemoCal.IntermediateRouting.Models
{
    public partial class Routing
    {
        

        /// <summary>
        /// Nombre del proveedor del convenio.
        /// </summary>
        [Required]
        public string Provider { get; set; }

        /// <summary>
        /// Identificador del convenio (primeros 4 dígitos del número de referencia).
        /// </summary>
        [Required]
        public string Identifier { get; set; }

        [Required]
		[JsonConverter(typeof(StringEnumConverter))]
        public Type Type { get; set; }

        /// <summary>
        /// URL del servicio Web proporcionado por el convenio.
        /// </summary>
        [Required]
        public string Endpoint { get; set; }

        /// <summary>
        /// Método HTTP en caso de ser REST, o nombre de capacidad si es SOAP.
        /// </summary>
        [Required]
        public string Action { get; set; }

        /// <summary>
        /// Transformación de Request.
        /// </summary>
        [Required]
        public string XSLTRequest { get; set; }

        /// <summary>
        /// Transformación de Response.
        /// </summary>
        [Required]
        public string XSLTResponse { get; set; }
    } // end class

} // end Models namespace

