// Template: Models (ApiEnum.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace DemoCal.IntermediateRouting.Models
{
    public enum Type
    {
		SOAP, REST    
    }

}
